//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliverySystemDBConnection : DbContext
    {
        public DeliverySystemDBConnection()
            : base("name=DeliverySystemDBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PackageHistory> PackageHistories { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<ProcCenter> ProcCenters { get; set; }
        public virtual DbSet<ScheduledDelivery> ScheduledDeliveries { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    }
}
