//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliverySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledDelivery
    {
        public int ScheduleId { get; set; }
        public int PackageId { get; set; }
        public short StaffId { get; set; }
        public System.DateTime ScheduledDateTime { get; set; }
        public short ScheduleType { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
